export default [
  {
    id: "0",
    image: require("../assets/quickImg/mcDonald.jpg"),
    name: "McDonald's",
    rating: 4.3,
    time: "30-40",
    offer: "50%",
  },
  {
    id: "1",
    image: require("../assets/quickImg/biriyani.jpg"),
    name: "Special Biriyani",
    rating: 3.8,
    time: "30-40",
    offer: "60%",
  },
  {
    id: "2",
    image: require("../assets/quickImg/Hyderabadi Bawarchi.jpg"),
    name: "Hyderabadi Bawarchi",
    rating: 4.1,
    time: "25-35",
    offer: "55%",
  },
  {
    id: "3",
    image: require("../assets/quickImg/Calofornia Burrito.jpg"),
    name: "Calofornia Burrito",
    rating: 4.5,
    time: "20-30",
    offer: "30%",
  },
  {
    id: "4",
    image: require("../assets/quickImg/udupi Utsav.jpeg"),
    name: "udupi Utsav",
    rating: 4.3,
    time: "30-40",
    offer: "60%",
  },
];
